language: go
go:
  - "1.12"
  - tip
env:
  - GO111MODULE=on
before_install:
  - go get github.com/mattn/goveralls
install:
  - go get -t ./...
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci

# for rocksdb
distro: bionic
addons:
  apt:
    packages:
      - libsnappy-dev
      - zlib1g-dev
      - libbz2-dev
      - librocksdb-dev
